In [119]:
from langchain_community.document_loaders import TextLoader

In [120]:
loader = TextLoader('sample-text.txt')
data = loader.load()

In [121]:
data[0].page_content

'The process of making maple syrup begins by tapping a spout (sometimes called a spile) into the sugar maple tree. The spile is inserted into the tree about 2 inches deep and the sap is collected as it flows out. The sap is then taken to a sugar shack where it is boiled down to concentrate the sugars. As the sap boils, water in the sap is evaporated and the syrup becomes more and more thick. Once the syrup reaches the right sugar content, which is usually when the boiling point reaches 219 degrees Fahrenheit, it is bottled and enjoyed.'

In [122]:
from langchain_community.document_loaders import CSVLoader
loader = CSVLoader('movies.csv', source_column='title')
data = loader.load()

In [123]:
data[1].metadata

{'source': 'Doctor Strange in the Multiverse of Madness', 'row': 1}

In [124]:
from langchain_community.document_loaders import UnstructuredURLLoader

In [133]:
loader = UnstructuredURLLoader(urls = [
    "https://www.moneycontrol.com/news/business/markets/wall-street-rises-as-tesla-soars-on-ai-optimism-11351111.html",
    "https://www.moneycontrol.com/news/business/tata-motors-launches-punch-icng-price-starts-at-rs-7-1-lakh-11098751.html",
])
data = loader.load()

In [134]:
data[0]

Document(metadata={'source': 'https://www.moneycontrol.com/news/business/markets/wall-street-rises-as-tesla-soars-on-ai-optimism-11351111.html'}, page_content='English\n\nHindi\n\nGujarati\n\nSpecials\n\nMy Alerts\n\nGo Ad-Free\n\nHello, Login\n\nHello, Login\n\nLog-inor Sign-Up\n\nMy Account\n\nMy Profile\n\nMy Portfolio\n\nMy Watchlist\n\nMy Alerts\n\nMy Messages\n\nPrice Alerts\n\nMy Profile\n\nMy PRO\n\nMy Portfolio\n\nMy Watchlist\n\nMy Alerts\n\nMy Messages\n\nPrice Alerts\n\nLogout\n\nLoans up to ₹50 LAKHS\n\nFixed Deposits\n\nCredit CardsLifetime Free\n\nCredit Score\n\nLoan against MFs\n\nChat with Us\n\nDownload App\n\nFollow us on:\n\nNetwork 18\n\n>->\n\nMoneycontrol\n\nGo PRO NowPRO\n\nMoneycontrol PRO\n\nBusiness\n\nMarkets\n\nStocks\n\nEconomy\n\nCompanies\n\nTrends\n\nIPO\n\nOpinion\n\nEV Special\n\nEco Pulse\n\nMC Learn\n\nTrending Topics\n\nSensex Today\n\nLenskart Share Price\n\nPaytm Shares\n\nBuzzing Stocks\n\nOnEMI Tech Shares\n\nWall Street rises as Tesla soars on AI optimism\n\nTesla (TSLA.O) rallied 10% after Morgan Stanley upgraded the electric car maker to "overweight" from "equal-weight," saying its Dojo supercomputer could boost the company\'s market value by nearly $600 billion.\n\nReuters\n\nSeptember 12, 2023 / 06:56 IST\n\njoin Us On WhatsApp\n\nFollow Us On Google\n\nAdd as a Preferred Source on Google\n\n\n\nWall Street rises as Tesla soars on AI optimism\n\nReuters\n\nfirst published: Sep 12, 2023 06:24 am\n\nDiscover the latest Business News, Sensex, and Nifty updates. Obtain Personal Finance insights, tax queries, and expert opinions on Moneycontrol or download the Moneycontrol App to stay updated!\n\nSubscribe to Tech Newsletters\n\nOn Saturdays\n\nFind the best of Al News in one place, specially curated for you every weekend.\n\nDaily-Weekdays\n\nStay on top of the latest tech trends and biggest startup news.\n\nSubscribe\n\nTrending news\n\n\'Thalapathy fan craze\': Kerala couple sets off on a 650-km walk to meet Tamil Nadu CM Vijay\n\n\'Company spends Rs 3,700 daily\': Gurgaon employee\'s Rs 81,400 monthly office perks stuns internet\n\nFailed JEE twice, faced 520 job rejections: Rohtak man shares reality behind landing a role at Google\n\nVijay\'s swearing-in ceremony is full-circle moment at Chennai\'s Nehru Stadium where fans once claimed he was humiliated by former CM Jayalalithaa\n\nTrisha Krishnan hugs Vijay\'s mother, greets family during his CM oath ceremony amid ongoing relationship rumours: Watch\n\nWhen Thalapathy Vijay saved Thala Dhoni: How TVK\'s Vijay came to rescue CSK\'s Dhoni in \'GOAT\' style\n\nWho holds highest qualification? TVK chief Vijay vs Wife Sangeetha vs Trisha Krishnan\n\nHappy Mother’s Day: Why Crocodile moms are among the most \'protective\' in the animal kingdom?\n\nAP POLYCET Results 2026 OUT @ polycetap.ap.gov.in today, download rank card here\n\nQuote of the day: "A man can be happy with any woman as long as he does not love her" — Oscar Wilde’s brutal take on love and relationships\n\nApple MacBook Neo gets its first big discount of flat Rs 10,000 on Amazon sale: All the details\n\nTelegram CEO Pavel Durov backs Elon Musk, says ‘free world should stand with X’ amid France probe into platform\n\nMet Gala 2026: Who is Sudha Reddy, the Hyderabad-based billionaire who wore Rs 142 crore necklace?\n\nIs hantavirus the new Covid? The truth behind over 50% fatality rate and more\n\nMumbai doctor shares Japanese habits to help you live longer; says they don’t do intermittent fasting or take collagen supplements\n\nAdvisory Alert:\n\nmoneycontrol\n\nFollow Us On:\n\nFacebook\n\ntwitter\n\ninstagram\n\nlinkedin\n\nyoutube\n\nStocks:\n\nA\n\nB\n\nC\n\nD\n\nE\n\nF\n\nG\n\nH\n\nI\n\nJ\n\nK\n\nL\n\nM\n\nN\n\nO\n\nP\n\nQ\n\nR\n\nS\n\nT\n\nU\n\nV\n\nW\n\nX\n\nY\n\nZ\n\nOthers\n\nTrending Topics\n\nSensex Today Vijay Government Formation Live SSC Result 2026 Maharashtra US Iran News Live Madhyamik Result 2026 Live Gold Price Today Bajaj Auto Share Price Tata Trusts Sridhar Vembu TN Plus Two Result\n\nNews\n\nBusiness Markets Stocks India News City News Economy Mutual Funds Personal Finance IPO News Startups\n\nMarkets\n\nHome Currencies Commodities Pre-Market IPO Global Market Bonds Silver MCX Price Gold MCX Price\n\nPersonal Finance\n\nHome Loans up to 50 Lakhs Credit Cards Lifetime Free Finance TrackerNew Fixed Deposits Fixed Deposit Comparison Fixed Income\n\nMutual Funds\n\nHome Performance Tracker Top Ranked Funds ETFs Mutual Fund Screener\n\nTools\n\nIncome Tax Calculator EMI Calculator Retirement Planning Gratuity Calculator Petrol Price in India Diesel Price in India IFSC Code\n\nCommunity\n\nStock Markets\n\nNetwork 18 Sites\n\nNews18 Firstpost CNBC TV18 News18 Hindi Cricketnext Overdrive\n\nQuick Links\n\nAbout Us Contact Us Advisory Alert Advertise with Us SupportDisclaimer Privacy Policy Cookie Policy Terms & Conditions Financial Terms (Glossary) Sitemap Investors\n\nDownload MC Apps:\n\n\n\n\n\n\n\nCopyright © Network18 Media & Investments Limited. All rights reserved. Reproduction of news articles, photos, videos or any other content in whole or in part in any form or medium without express written permission of moneycontrol.com is prohibited.\n\nYou got 30 Day’s Trial of\n\nMoneycontrol Pro\n\nMoneycontrol Pro\n\nGrab it Now\n\nAd-Free Experience\n\nTop Articles from Financial Times\n\nTop Articles from Financial Times\n\nActionable Insights\n\nMC Research\n\nEconomic Calendar\n\n& Many More\n\n& Many More\n\nYou are already a Moneycontrol Pro user.\n\nOutskill - Master AI\n\nOutskill - Master AI\n\nFaizan Javed')

In [127]:
from langchain_text_splitters import RecursiveCharacterTextSplitter

In [135]:
text_splitter = RecursiveCharacterTextSplitter(
    chunk_size = 1000,
    chunk_overlap = 200
)

docs = text_splitter.split_documents(data)
len(docs)

11

In [136]:
docs[0]

Document(metadata={'source': 'https://www.moneycontrol.com/news/business/markets/wall-street-rises-as-tesla-soars-on-ai-optimism-11351111.html'}, page_content='English\n\nHindi\n\nGujarati\n\nSpecials\n\nMy Alerts\n\nGo Ad-Free\n\nHello, Login\n\nHello, Login\n\nLog-inor Sign-Up\n\nMy Account\n\nMy Profile\n\nMy Portfolio\n\nMy Watchlist\n\nMy Alerts\n\nMy Messages\n\nPrice Alerts\n\nMy Profile\n\nMy PRO\n\nMy Portfolio\n\nMy Watchlist\n\nMy Alerts\n\nMy Messages\n\nPrice Alerts\n\nLogout\n\nLoans up to ₹50 LAKHS\n\nFixed Deposits\n\nCredit CardsLifetime Free\n\nCredit Score\n\nLoan against MFs\n\nChat with Us\n\nDownload App\n\nFollow us on:\n\nNetwork 18\n\n>->\n\nMoneycontrol\n\nGo PRO NowPRO\n\nMoneycontrol PRO\n\nBusiness\n\nMarkets\n\nStocks\n\nEconomy\n\nCompanies\n\nTrends\n\nIPO\n\nOpinion\n\nEV Special\n\nEco Pulse\n\nMC Learn\n\nTrending Topics\n\nSensex Today\n\nLenskart Share Price\n\nPaytm Shares\n\nBuzzing Stocks\n\nOnEMI Tech Shares\n\nWall Street rises as Tesla soars on AI optimism\n\nTesla (TSLA.O) rallied 10% after Morgan Stanley upgraded the electric car maker to "overweight" from "equal-weight," saying its Dojo supercomputer could boost the company\'s market value by nearly $600 billion.\n\nReuters\n\nSeptember 12, 2023 / 06:56 IST')

In [137]:
from langchain_openai import OpenAIEmbeddings
from langchain_community.vectorstores import FAISS
import faiss

embeddings = OpenAIEmbeddings(api_key=api_key)
vector_index =  FAISS.from_documents(docs, embeddings)

In [142]:
vector_index.save_local("faiss_index")

In [139]:
import pickle
#file_path = "vector_index.pkl"
# with open(file_path, "wb") as f:
#     pickle.dump(vector_index, f)

In [157]:
file_path = "faiss_index"
vectorIndex = FAISS.load_local(
    "faiss_index",
    embeddings,
    allow_dangerous_deserialization=True
)

In [ ]:
retriever = vectorIndex.as_retriever(
    search_kwargs={"k": 4},
     search_type="similarity"
)

In [ ]:
retriever

VectorStoreRetriever(tags=['FAISS', 'OpenAIEmbeddings'], vectorstore=<langchain_community.vectorstores.faiss.FAISS object at 0x7a7fff3ce8d0>, search_kwargs={'k': 4})

In [ ]:
import langchain_core

query = "what is the price of Tiago ICNG?"
docs = retriever.invoke(query)
# Display retrieved documents
# for i, doc in enumerate(docs, 1):
#     print(f"\n--- Document {i} ---")
#     print(doc.page_content)
#     print("Metadata:", doc.metadata)

In [183]:
from langchain_openai import OpenAI
llm = llm = OpenAI(api_key = api_key, temperature=0.5)
import os
from dotenv import load_dotenv
load_dotenv()
api_key = os.getenv("OPENAI_KEY")

In [ ]:
from langchain_core.prompts  import ChatPromptTemplate 
prompt = ChatPromptTemplate.from_template(
"""
Use the following portion of a long document ot see if any of the text is relevant to answer the question.
Return any relevant text verbatim.

Context:
{context}

Question:
{question}

Answer:
"""
)
from langchain_core.runnables import RunnablePassthrough 
chain = ({"context": retriever, "question": RunnablePassthrough()} |
            prompt|llm
        )
langchain_core.globals.set_debug(False) 
chain.invoke(query)

'\nThe price of Tiago ICNG starts at Rs. 7.1 lakh. Source: https://www.moneycontrol.com/news/business/tata-motors-launches-punch-icng-price-starts-at-rs-7-1-lakh-11098751.html'

In [223]:
langchain_core.globals.set_debug(True) 
map_results = []
for doc in docs:
    result = llm.invoke(
        prompt.format(
            context=doc.page_content,
            question=query
        )
    )
    map_results.append(result)
map_prompt = ChatPromptTemplate.from_template("""
"Given the following extracted parts of a long document and a question, create a final answer with references (\"SOURCES\"). \nIf you don't know the answer, just say that you don't know. Don't try to make up an answer.\nALWAYS return a \"SOURCES\" part in your answer.

Documents:
{document}
                                              
Question:
{question}                       

Final answer:
""")
portioned_responses = "\n\n".join(map_results)
prompt = map_prompt.format(
    document=portioned_responses,
    question=query
)

final_answer = llm.invoke(prompt)
print(final_answer)

[llm/start] [llm:OpenAI] Entering LLM run with input:
{
  "prompts": [
    "Human: \nUse the following portion of a long document ot see if any of the text is relevant to answer the question.\nReturn any relevant text verbatim.\n\nContext:\nEco Pulse\n\nMC Learn\n\nTrending Topics\n\nSensex Live\n\nLenskart Block Deal\n\nGift Nifty\n\nPetrol and Diesel Prices Today\n\nOnEMI Technology IPO\n\nTata Motors launches Punch iCNG, price starts at Rs 7.1 lakh\n\nThe Punch iCNG is equipped with the company's proprietary twin-cylinder technology with enhanced safety features like a micro-switch to keep the car switched off at the time of refuelling and thermal incident protection that cuts off CNG supply to the engine and releases gas into the atmosphere, Tata Motors said in a statement.\n\nPTI\n\nAugust 04, 2023 / 14:17 IST\n\njoin Us On WhatsApp\n\nFollow Us On Google\n\nAdd as a Preferred Source on Google\n\n\n\nTata Motors launches Punch iCNG, price starts at Rs 7.1 lakh\n\nTEL\n\nWatchlist\n\nPortfolio\n\nMessage\n\nFollow\n\nDay High\n\nDay Low\n\nVolume (NSE)\n\nMore\n\nAdd to Watchlist\n\nPTI\n\nfirst published: Aug 4, 2023 02:17 pm\n\nQuestion:\nwhat is the price of Tiago ICNG?\n\nAnswer:"
  ]
}
[llm/end] [llm:OpenAI] [533ms] Exiting LLM run with output:
{
  "generations": [
    [
      {
        "text": "The price of Tata Motors' Punch iCNG starts at Rs 7.1 lakh.",
        "generation_info": {
          "finish_reason": "stop",
          "logprobs": null
        },
        "type": "Generation"
      }
    ]
  ],
  "llm_output": {
    "token_usage": {
      "completion_tokens": 19,
      "prompt_tokens": 269,
      "total_tokens": 288
    },
    "model_name": "gpt-3.5-turbo-instruct"
  },
  "run": null,
  "type": "LLMResult"
}
[llm/start] [llm:OpenAI] Entering LLM run with input:
{
  "prompts": [
    "Human: \nUse the following portion of a long document ot see if any of the text is relevant to answer the question.\nReturn any relevant text verbatim.\n\nContext:\nEnglish\n\nHindi\n\nGujarati\n\nSpecials\n\nMy Alerts\n\nGo Ad-Free\n\nHello, Login\n\nHello, Login\n\nLog-inor Sign-Up\n\nMy Account\n\nMy Profile\n\nMy Portfolio\n\nMy Watchlist\n\nMy Alerts\n\nMy Messages\n\nPrice Alerts\n\nMy Profile\n\nMy PRO\n\nMy Portfolio\n\nMy Watchlist\n\nMy Alerts\n\nMy Messages\n\nPrice Alerts\n\nLogout\n\nLoans up to ₹50 LAKHS\n\nFixed Deposits\n\nCredit CardsLifetime Free\n\nCredit Score\n\nLoan against MFs\n\nChat with Us\n\nDownload App\n\nFollow us on:\n\nNetwork 18\n\n>->\n\nMoneycontrol\n\nGo PRO NowPRO\n\nMoneycontrol PRO\n\nBusiness\n\nMarkets\n\nStocks\n\nEconomy\n\nCompanies\n\nTrends\n\nIPO\n\nOpinion\n\nEV Special\n\nEco Pulse\n\nMC Learn\n\nTrending Topics\n\nSensex Live\n\nLenskart Block Deal\n\nGift Nifty\n\nPetrol and Diesel Prices Today\n\nOnEMI Technology IPO\n\nTata Motors launches Punch iCNG, price starts at Rs 7.1 lakh\n\nQuestion:\nwhat is the price of Tiago ICNG?\n\nAnswer:"
  ]
}
[llm/end] [llm:OpenAI] [510ms] Exiting LLM run with output:
{
  "generations": [
    [
      {
        "text": "The price of Tata Motors' Tiago iCNG starts at Rs 7.1 lakh.",
        "generation_info": {
          "finish_reason": "stop",
          "logprobs": null
        },
        "type": "Generation"
      }
    ]
  ],
  "llm_output": {
    "token_usage": {
      "completion_tokens": 20,
      "prompt_tokens": 266,
      "total_tokens": 286
    },
    "model_name": "gpt-3.5-turbo-instruct"
  },
  "run": null,
  "type": "LLMResult"
}
[llm/start] [llm:OpenAI] Entering LLM run with input:
{
  "prompts": [
    "Human: \nUse the following portion of a long document ot see if any of the text is relevant to answer the question.\nReturn any relevant text verbatim.\n\nContext:\nEnglish\n\nHindi\n\nGujarati\n\nSpecials\n\nMy Alerts\n\nGo Ad-Free\n\nHello, Login\n\nHello, Login\n\nLog-inor Sign-Up\n\nMy Account\n\nMy Profile\n\nMy Portfolio\n\nMy Watchlist\n\nMy Alerts\n\nMy Messages\n\nPrice Alerts\n\nMy Profile\n\nMy PRO\n\nMy Portfolio\n\nMy Watchlist\n\nMy Alerts\n\nMy Messages\n\nPrice Alerts\n\nLogout\n\nLoans up to ₹50 LAKHS\n\nFixed Deposits\n\nCredit CardsLifetime Free\n\nCredit Score\n\nLoan against MFs\n\nChat with Us\n\nDownload App\n\nFollow us on:\n\nNetwork 18\n\n>->\n\nMoneycontrol\n\nGo PRO NowPRO\n\nMoneycontrol PRO\n\nBusiness\n\nMarkets\n\nStocks\n\nEconomy\n\nCompanies\n\nTrends\n\nIPO\n\nOpinion\n\nEV Special\n\nEco Pulse\n\nMC Learn\n\nTrending Topics\n\nSensex Today\n\nLenskart Share Price\n\nPaytm Shares\n\nBuzzing Stocks\n\nOnEMI Tech Shares\n\nWall Street rises as Tesla soars on AI optimism\n\nTesla (TSLA.O) rallied 10% after Morgan Stanley upgraded the electric car maker to \"overweight\" from \"equal-weight,\" saying its Dojo supercomputer could boost the company's market value by nearly $600 billion.\n\nReuters\n\nSeptember 12, 2023 / 06:56 IST\n\nQuestion:\nwhat is the price of Tiago ICNG?\n\nAnswer:"
  ]
}
[llm/end] [llm:OpenAI] [415ms] Exiting LLM run with output:
{
  "generations": [
    [
      {
        "text": "There is no information about the price of Tiago ICNG in the given portion of the document.",
        "generation_info": {
          "finish_reason": "stop",
          "logprobs": null
        },
        "type": "Generation"
      }
    ]
  ],
  "llm_output": {
    "token_usage": {
      "completion_tokens": 20,
      "prompt_tokens": 319,
      "total_tokens": 339
    },
    "model_name": "gpt-3.5-turbo-instruct"
  },
  "run": null,
  "type": "LLMResult"
}
[llm/start] [llm:OpenAI] Entering LLM run with input:
{
  "prompts": [
    "Human: \nUse the following portion of a long document ot see if any of the text is relevant to answer the question.\nReturn any relevant text verbatim.\n\nContext:\nApple MacBook Neo gets its first big discount of flat Rs 10,000 on Amazon sale: All the details\n\nTelegram CEO Pavel Durov backs Elon Musk, says ‘free world should stand with X’ amid France probe into platform\n\nMet Gala 2026: Who is Sudha Reddy, the Hyderabad-based billionaire who wore Rs 142 crore necklace?\n\nIs hantavirus the new Covid? The truth behind over 50% fatality rate and more\n\nMumbai doctor shares Japanese habits to help you live longer; says they don’t do intermittent fasting or take collagen supplements\n\nAdvisory Alert:\n\nmoneycontrol\n\nFollow Us On:\n\nFacebook\n\ntwitter\n\ninstagram\n\nlinkedin\n\nyoutube\n\nStocks:\n\nA\n\nB\n\nC\n\nD\n\nE\n\nF\n\nG\n\nH\n\nI\n\nJ\n\nK\n\nL\n\nM\n\nN\n\nO\n\nP\n\nQ\n\nR\n\nS\n\nT\n\nU\n\nV\n\nW\n\nX\n\nY\n\nZ\n\nOthers\n\nTrending Topics\n\nSensex Today Vijay Government Formation Live SSC Result 2026 Maharashtra US Iran News Live Madhyamik Result 2026 Live Gold Price Today Bajaj Auto Share Price Tata Trusts Sridhar Vembu TN Plus Two Result\n\nNews\n\nQuestion:\nwhat is the price of Tiago ICNG?\n\nAnswer:"
  ]
}
[llm/end] [llm:OpenAI] [751ms] Exiting LLM run with output:
{
  "generations": [
    [
      {
        "text": "As this portion of the document does not contain any relevant information about Tiago ICNG, there is no text to return.",
        "generation_info": {
          "finish_reason": "stop",
          "logprobs": null
        },
        "type": "Generation"
      }
    ]
  ],
  "llm_output": {
    "token_usage": {
      "completion_tokens": 25,
      "prompt_tokens": 301,
      "total_tokens": 326
    },
    "model_name": "gpt-3.5-turbo-instruct"
  },
  "run": null,
  "type": "LLMResult"
}
[llm/start] [llm:OpenAI] Entering LLM run with input:
{
  "prompts": [
    "Human: \n\"Given the following extracted parts of a long document and a question, create a final answer with references (\"SOURCES\"). \nIf you don't know the answer, just say that you don't know. Don't try to make up an answer.\nALWAYS return a \"SOURCES\" part in your answer.\n\nDocuments:\nThe price of Tata Motors' Punch iCNG starts at Rs 7.1 lakh.\n\nThe price of Tata Motors' Tiago iCNG starts at Rs 7.1 lakh.\n\nThere is no information about the price of Tiago ICNG in the given portion of the document.\n\nAs this portion of the document does not contain any relevant information about Tiago ICNG, there is no text to return.\n\nQuestion:\nwhat is the price of Tiago ICNG?                       \n\nFinal answer:"
  ]
}
[llm/end] [llm:OpenAI] [703ms] Exiting LLM run with output:
{
  "generations": [
    [
      {
        "text": "The price of Tata Motors' Tiago iCNG starts at Rs 7.1 lakh. SOURCES: Tata Motors' official website (https://www.tatamotors.com/press/tiago-icng-is-now-available-in-india/).",
        "generation_info": {
          "finish_reason": "stop",
          "logprobs": null
        },
        "type": "Generation"
      }
    ]
  ],
  "llm_output": {
    "token_usage": {
      "completion_tokens": 54,
      "prompt_tokens": 169,
      "total_tokens": 223
    },
    "model_name": "gpt-3.5-turbo-instruct"
  },
  "run": null,
  "type": "LLMResult"
}
The price of Tata Motors' Tiago iCNG starts at Rs 7.1 lakh. SOURCES: Tata Motors' official website (https://www.tatamotors.com/press/tiago-icng-is-now-available-in-india/).

In [5]:
a = ['1','2','34']
b = "\n--\n".join(a)
b

'1\n--\n2\n--\n34'

In [38]:
import pandas as pd

In [41]:
df = pd.read_csv('sample_text.csv')
df.head()

                                                text category
0      Meditation and yoga can improve mental health   Health
1  Fruits, whole grains and vegetables helps cont...   Health
2  These are the latest fashion trends for this week  Fashion
3  Vibrant color jeans for male are becoming a trend  Fashion
4                 The concert starts at 7 PM tonight    Event

In [44]:
from sentence_transformers import SentenceTransformer

encoder = SentenceTransformer("all-mpnet-base-v2")

# Remove missing values and convert to strings
texts = df["text"].dropna().astype(str).tolist()

# Generate embeddings
vectors = encoder.encode(texts)

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 4870.47it/s]

In [45]:
vectors.shape

(8, 768)

In [47]:
import faiss

dim = vectors.shape[1]

# L2 (Euclidean distance) index
index = faiss.IndexFlatL2(dim)

print(index)

<faiss.swigfaiss_avx2.IndexFlatL2; proxy of <Swig Object of type 'faiss::IndexFlatL2 *' at 0x7a805865fc90> >

In [48]:
index.add(vectors)

In [49]:
search_query = 'i want to buy a polo t-shirt'
vector  = encoder.encode(search_query)
vector.shape

(768,)

In [52]:
[vector]

[array([ 1.03882849e-02,  2.78686099e-02, -1.18618747e-02,  1.81327239e-02,
         1.21983048e-03, -1.42995743e-02,  1.96229275e-02,  2.07198393e-02,
        -2.23660767e-02,  4.75626737e-02,  1.77976228e-02, -8.00333917e-03,
         2.53419485e-02,  5.26148528e-02,  8.44937935e-03, -1.63944252e-02,
         1.02661615e-02, -2.74856184e-02,  8.37067068e-02, -1.52885346e-02,
         1.67682581e-02, -3.97141092e-03, -2.74348464e-02,  5.02091758e-02,
        -8.36521015e-03, -4.74075824e-02,  2.36915853e-02, -1.01186484e-02,
        -2.82840226e-02,  7.94262160e-03,  4.21435833e-02, -4.19375440e-03,
        -1.91232320e-02, -3.12785432e-02,  1.24685050e-06, -1.04428222e-02,
        -2.19971295e-02, -8.66927952e-02, -1.88496127e-03, -2.54772231e-02,
        -9.72972345e-03,  7.93310702e-02, -3.55963558e-02, -3.05376569e-04,
        -1.12392223e-02, -3.88932452e-02,  5.49313799e-02,  1.35207951e-01,
        -8.19147602e-02,  1.18785053e-02, -9.01844073e-03,  1.92544386e-02,
        -2.82723568e-02, -3.29267010e-02, -2.20106803e-02, -4.29836027e-02,
         3.70104611e-02, -4.80649099e-02,  9.49255843e-03,  3.51585858e-02,
         4.88772392e-02, -3.28933299e-02, -1.24120461e-02, -1.64293069e-02,
         3.93721387e-02,  2.69109569e-02,  6.15458600e-02, -4.14121151e-03,
         1.75675433e-02,  1.53993312e-02,  9.60060488e-03, -5.69586700e-04,
        -4.83582541e-02,  4.25832197e-02,  1.10985739e-02, -4.66182418e-02,
        -2.10590730e-03, -5.81461489e-02,  1.40412673e-02,  1.00883590e-02,
        -2.44589709e-02,  1.42714214e-02, -2.10582297e-02,  7.38854334e-02,
        -2.23949067e-02,  1.38753057e-02, -1.33593671e-03,  9.21318959e-03,
        -2.84222625e-02, -4.04207176e-03, -1.71393212e-02, -8.46521743e-03,
        -2.83984058e-02, -3.69299464e-02, -9.47201252e-02, -3.26580256e-02,
         2.60049552e-02,  1.31179066e-02,  1.51670743e-02, -2.12378148e-03,
         1.48177966e-02,  1.37817021e-02,  1.25303809e-02, -5.01476182e-03,
         3.56063098e-02,  5.93453944e-02, -5.03397360e-02, -9.55991633e-03,
        -7.23669007e-02,  9.45842452e-03,  1.54202785e-02, -7.03747524e-03,
        -3.10014859e-02, -8.86357389e-03, -2.98000220e-02, -8.84007588e-02,
        -2.25059055e-02, -3.25824246e-02,  4.78070378e-02,  2.14029988e-03,
         1.37759582e-03, -1.25066005e-02, -1.15712658e-02,  2.34021638e-02,
         3.43835400e-03,  2.69363262e-02, -6.23307191e-02, -5.29253343e-03,
         1.73165661e-03,  3.20439488e-02,  2.13116364e-04, -1.54123483e-02,
         5.08342758e-02, -4.52312231e-02, -1.67428460e-02, -3.47918645e-02,
        -4.16715071e-02, -2.34929267e-02,  2.40790797e-03, -2.15250738e-02,
         3.07013257e-03,  2.54970994e-02,  3.60133201e-02,  2.68477965e-02,
        -4.22385857e-02, -2.45388523e-02,  3.93797942e-02,  6.31312048e-03,
         2.03843676e-02, -2.22934410e-02, -7.87318684e-03, -1.47401197e-02,
         4.87235487e-02, -2.55933497e-02, -1.08920848e-02, -3.37022655e-02,
         4.69094738e-02,  1.95821431e-02,  4.13408177e-03,  2.72842757e-02,
         4.72939631e-04,  2.55070720e-02, -5.26176319e-02,  3.57674398e-02,
        -5.46484347e-03, -3.90752256e-02, -4.51455638e-02, -1.37631325e-02,
         5.50720617e-02,  3.80344130e-02, -4.58984822e-02,  4.83392272e-03,
        -2.92574596e-02, -4.76553151e-03,  9.17752907e-02, -9.70400125e-02,
         1.05631806e-01, -5.64410836e-02, -6.33300990e-02,  3.45335677e-02,
        -5.77132478e-02, -1.21777304e-01,  9.45344195e-03,  2.02731472e-02,
         2.63031870e-02,  3.96900903e-03, -3.88276391e-02, -1.57009158e-02,
        -3.47952098e-02, -3.07988133e-02,  3.24620456e-02, -4.84479256e-02,
         4.39473893e-03, -1.72206815e-02,  1.15603274e-04, -3.72782126e-02,
        -5.17302789e-02, -1.91914402e-02, -3.10722571e-02,  4.77238139e-03,
        -5.49006462e-02, -1.40048712e-02,  2.99301632e-02,  9.23176259e-02,
        -2.96304319e-02,  2.45515760e-02,  3.50713469e-02, -5.64087648e-03,
         1.57488864e-02,  2.08431538e-02,  5.11531755e-02,  7.25737447e-03,
         4.40721866e-03, -2.58072317e-02,  4.99891769e-03, -1.47746783e-03,
        -4.42322204e-03,  4.48388122e-02,  7.79227614e-02,  1.65748019e-02,
        -3.80822569e-02,  3.76828276e-02,  1.02415681e-01, -1.61059089e-02,
         7.32476711e-02, -1.11488095e-02,  3.81629243e-02,  2.02278681e-02,
        -1.23596815e-02,  2.38338672e-02, -2.99291871e-02, -7.08033983e-03,
         1.23009812e-02, -6.69542141e-03, -6.65793270e-02,  6.94696531e-02,
         1.02031808e-02, -2.23913025e-02, -1.79656502e-02, -3.10913622e-02,
        -3.04419845e-02, -2.43375469e-02,  2.62913723e-02, -1.44890938e-02,
        -3.44526507e-02,  3.69894388e-03,  2.34961826e-02, -2.20465753e-02,
        -6.40620217e-02, -3.29653248e-02, -1.13152498e-02,  4.46261279e-02,
         2.82178577e-02, -1.32326512e-02, -2.48316713e-02, -4.16193716e-02,
        -3.17104645e-02, -2.90310872e-03, -2.58374307e-02, -2.38407385e-02,
         4.09953222e-02, -3.72038856e-02,  3.80427055e-02,  2.60184556e-02,
         3.78452279e-02, -1.22929662e-02, -1.78747196e-02,  2.22685039e-02,
        -1.39293475e-02,  3.33371782e-03, -1.01043517e-02, -9.42679048e-02,
         2.93328185e-02, -2.11533830e-02, -8.28085653e-03,  9.39181447e-03,
         7.01195300e-02, -2.47647986e-02, -7.45414337e-03,  1.81595348e-02,
         2.10113879e-02,  5.30432202e-02, -1.83114354e-02,  2.45678499e-02,
         1.81325953e-02, -1.36736706e-02, -2.25673220e-03,  2.27259528e-02,
        -1.32561587e-02,  5.31734675e-02,  2.84621795e-03, -1.26052415e-02,
         5.37055209e-02, -2.62218080e-02,  6.28262013e-02, -3.38792689e-02,
         1.24346297e-02,  3.83223197e-03,  2.31522731e-02, -7.25013241e-02,
        -4.14393237e-03, -4.29395549e-02, -9.25684813e-03, -1.02920169e-02,
        -2.94400025e-02, -1.51161617e-02,  1.03489021e-02, -8.83043092e-03,
         7.79081322e-03,  6.15880378e-02, -2.56217904e-02,  2.67890412e-02,
        -3.48654985e-02, -3.35104354e-02,  4.58869264e-02,  2.87142508e-02,
        -1.73843298e-02,  9.46802124e-02, -2.42618285e-02,  2.83706877e-02,
         5.47285052e-03, -3.05396412e-02, -2.04882361e-02,  1.14951013e-02,
        -2.06156950e-02, -4.73047383e-02, -5.66258852e-04,  2.54014134e-02,
        -4.44825739e-02, -3.05528753e-02, -2.27482244e-02,  5.34625677e-03,
        -1.77380461e-02,  8.93084425e-03,  6.29967730e-03, -4.71266843e-02,
         9.71081015e-03, -1.98281333e-02, -1.95309110e-02,  2.61490270e-02,
         2.61223759e-03, -2.84732375e-02, -8.45035072e-03, -6.73167855e-02,
        -8.53152126e-02, -3.01742647e-02,  3.68127003e-02,  2.59252414e-02,
        -6.74629956e-02, -5.72894290e-02, -1.90711189e-02, -2.98832599e-02,
        -1.49018634e-02, -6.44184602e-03, -1.42151751e-02,  3.73985879e-02,
         1.12892699e-03,  2.28629299e-02, -4.47167940e-02,  2.30516512e-02,
         6.28953450e-04,  4.42759097e-02,  2.46649999e-02,  3.51332575e-02,
        -3.61626148e-02, -4.75540347e-02,  1.82497762e-02,  3.07629500e-02,
         1.00457750e-03, -1.84898730e-02, -2.19331578e-05,  7.50036091e-02,
         3.62004675e-02,  6.58764988e-02, -1.86647438e-02,  4.20116931e-02,
        -2.29520560e-03,  6.42547831e-02,  5.11614271e-02, -1.55825522e-02,
        -7.13897753e-04,  3.42612527e-02, -6.07559597e-03,  2.43100170e-02,
        -1.24313235e-02, -4.36682813e-02,  2.47560255e-02, -3.65800150e-02,
         2.03334186e-02, -3.50793228e-02,  1.50017394e-02,  7.63921291e-02,
         6.04431331e-02,  6.65943921e-02,  3.30558023e-03,  3.46694328e-02,
        -1.60531851e-03, -2.37293001e-02,  9.55965929e-03, -8.56767502e-03,
        -1.43413665e-02,  9.41571370e-02,  3.45746800e-02,  7.35701174e-02,
         2.54632197e-02, -3.96389477e-02,  2.52091140e-02,  7.53591806e-02,
        -3.82415466e-02, -3.73828933e-02, -5.41513413e-02,  2.40689181e-02,
        -3.08086891e-02, -6.20016549e-03, -7.64316041e-03, -3.59188393e-02,
         1.13590527e-03, -4.66336962e-03,  2.37279888e-02, -4.54728715e-02,
        -1.95230928e-03,  1.30089764e-02, -4.03874889e-02,  3.14237177e-02,
         3.25081460e-02,  2.98243463e-02, -7.06260907e-04, -8.04493204e-02,
        -1.45465862e-02, -1.17486110e-02, -3.25348116e-02,  3.16704698e-02,
        -4.22670208e-02,  6.71451166e-02, -1.01962581e-01, -3.84004153e-02,
        -1.90569460e-02,  5.59220761e-02,  7.67454412e-03,  5.18109724e-02,
         1.68128684e-02, -1.31116342e-02,  2.82037049e-03,  1.55520230e-03,
        -5.03726304e-04, -3.61106060e-02, -6.84428774e-03,  1.76924318e-02,
        -2.98450086e-02, -4.57745418e-02,  1.10833962e-02, -1.51629644e-02,
         3.66877439e-03,  8.08090270e-02, -1.80434827e-02, -1.02003082e-03,
        -4.84704098e-04,  3.22403125e-02, -1.65944658e-02,  1.84555701e-03,
         5.07567450e-02,  1.58889554e-02, -6.26497939e-02, -1.95618793e-02,
         4.34029512e-02, -5.68292737e-02,  1.05988301e-01, -4.80109155e-02,
         1.00577883e-02,  2.19855811e-02, -3.14385928e-02,  1.16583575e-02,
         3.97340693e-02, -1.13186818e-02,  5.83116636e-02,  2.77366186e-03,
         6.33229092e-02,  4.29549292e-02,  2.16283146e-02,  3.85456197e-02,
        -2.44158525e-02,  1.34006385e-02,  2.94844108e-03,  7.02531682e-03,
        -1.87546574e-02,  4.76556383e-02,  6.15999848e-02,  1.85416210e-02,
        -1.38640376e-02, -4.43654135e-02, -2.19828468e-02,  1.19858058e-02,
        -3.77185233e-02, -6.42945766e-02, -2.67555788e-02,  5.12968637e-02,
         2.78438367e-02, -6.28402233e-02, -3.17041129e-02,  2.21165530e-02,
        -1.41522773e-02, -6.07150514e-03,  7.16667846e-02,  1.14130341e-02,
         3.74977500e-03, -6.88136071e-02,  4.47597429e-02, -3.12532932e-02,
         1.41535569e-02, -3.08248904e-02, -7.57702219e-04, -5.60958171e-03,
         4.05325145e-02,  5.67520736e-04,  1.03435693e-02,  8.89484808e-02,
        -8.93701240e-03, -6.23020828e-02,  2.01754533e-02, -1.27847213e-02,
         1.61152203e-02, -1.23151047e-02,  2.49236114e-02,  2.02201996e-02,
        -2.01466642e-02,  4.14760001e-02, -2.72540357e-02, -3.96626033e-02,
        -2.26232018e-02,  1.40829175e-03,  1.52835278e-02, -6.26358986e-02,
         6.85891360e-02,  2.12807469e-02, -4.11787406e-02,  7.12969825e-02,
        -2.85411365e-02, -1.06836613e-02, -1.89546514e-02,  1.78563986e-02,
        -3.75272110e-02,  6.14903285e-04,  4.38691303e-02,  1.56059451e-02,
         3.15997028e-03,  5.58516709e-03, -5.97156445e-03,  2.85605490e-02,
        -9.22785420e-03,  9.27610975e-03,  2.80324817e-02,  6.93220943e-02,
        -3.44455093e-02, -2.25160159e-02,  2.57091969e-02, -4.39213619e-33,
        -3.64305526e-02, -2.59272475e-03,  9.11505613e-03,  3.95197570e-02,
         1.37440059e-02,  3.83441546e-03,  2.09220778e-03, -6.76695909e-03,
         1.25046019e-02, -1.33823641e-02, -1.84266537e-03,  1.20098032e-02,
         1.55763682e-02,  7.08818086e-04,  7.13026971e-02, -5.37558869e-02,
         2.44811494e-02, -4.40049730e-02, -1.36816567e-02, -1.33414520e-02,
        -2.93122977e-02, -1.21151488e-02,  6.02591746e-02,  1.02625703e-02,
         3.59789878e-02, -3.84313688e-02,  2.23757438e-02,  1.09116267e-02,
         6.93021938e-02,  1.61974784e-02, -3.05023678e-02,  4.06713262e-02,
        -3.92037369e-02, -3.48171890e-02,  4.40173149e-02,  2.78182942e-02,
        -5.45111811e-03, -2.34862920e-02,  9.80815012e-03,  2.96252966e-02,
         4.15044911e-02, -8.76813978e-02, -8.35824236e-02, -2.17031930e-02,
        -3.72131690e-02, -8.14555492e-03, -1.64230596e-02, -3.21031082e-03,
         7.74315419e-03, -4.88730073e-02, -3.05721234e-03, -2.07577702e-02,
         1.43916728e-02, -2.15989240e-02,  5.19237109e-02,  3.22398283e-02,
         2.97001507e-02,  6.64230362e-02,  3.49241793e-02,  6.32981434e-02,
         2.76506469e-02, -6.43676370e-02, -1.97427180e-02, -6.66220039e-02,
        -2.80176345e-02, -2.66223606e-02, -1.15307560e-02, -2.93887639e-03,
         2.88166348e-02, -3.48907039e-02,  1.28499093e-02,  2.38518361e-02,
        -2.04858799e-02,  3.24630253e-02,  2.07587108e-02,  3.60320285e-02,
         1.18891960e-02,  2.08263043e-02,  5.34499884e-02,  3.98998298e-02,
         1.93190412e-03,  4.08157185e-02,  1.73660889e-02,  1.62020605e-02,
        -3.99374142e-02, -5.42060398e-02, -9.92145762e-03, -2.20064465e-02,
         2.27758288e-02, -3.69535270e-03, -5.12674749e-02, -3.43792215e-02,
         2.70803161e-02,  6.55441685e-03, -8.59291852e-02, -6.78600073e-02,
        -6.93692174e-03,  1.56281106e-02, -6.14047423e-03,  1.97633933e-02,
        -2.56496333e-02, -8.55880696e-03, -6.69194851e-03, -1.37871476e-02,
        -1.60989761e-02, -6.38105813e-03,  4.70548943e-02, -3.73779330e-03,
        -2.61347629e-02,  9.47332010e-04,  5.62973088e-03, -4.70339544e-02,
        -2.40904242e-02, -1.03060178e-01,  3.95706147e-02,  1.86298173e-02,
         1.22608170e-02, -2.66108625e-02,  8.73115286e-03, -1.45035619e-02,
        -2.18206178e-02, -5.02304994e-02, -1.87203623e-02, -1.50403129e-02,
        -3.63761256e-03,  1.26317842e-02,  3.22695076e-02,  2.52542160e-02,
        -2.95263529e-02, -1.22713009e-02, -1.14217624e-02, -9.44963843e-03,
         1.85265648e-07, -3.20790559e-02,  2.90721897e-02,  1.50097478e-02,
         4.58585657e-02, -4.58980240e-02,  8.51313397e-02,  1.87606141e-02,
        -7.52922148e-03, -9.47738346e-03,  2.20605489e-02, -1.64591819e-02,
         1.37805985e-02, -5.93536720e-03,  1.98825561e-02, -1.72281638e-02,
        -5.15167750e-02,  7.51994103e-02, -2.18111947e-02,  1.31010393e-05,
        -4.08613570e-02, -2.18479391e-02,  7.75561929e-02,  6.59543499e-02,
         3.45364548e-02,  6.32862840e-03, -3.45287174e-02,  2.41718497e-02,
        -5.22142500e-02, -4.00037086e-03, -4.70076948e-02, -7.21944869e-03,
        -6.05985001e-02, -4.96257143e-03, -1.06797488e-02,  3.90087478e-02,
        -4.15892387e-03,  5.15687503e-02,  1.44929290e-02,  8.72994494e-03,
         5.83561920e-02, -4.20899689e-02, -3.73954792e-03, -4.08154391e-02,
        -3.81656587e-02,  2.13403627e-03,  3.52093764e-03, -6.06537051e-03,
        -2.75366735e-02, -1.17570534e-02, -2.33173347e-03,  2.78418865e-02,
        -2.67388932e-02,  2.94055697e-02, -3.15133557e-02, -4.89009498e-03,
        -3.41911404e-03,  4.42338251e-02,  1.56635568e-02,  1.01597952e-02,
        -8.11970383e-02, -8.73948557e-06,  4.35416847e-02, -3.40957474e-03,
         1.32463604e-01, -5.27367890e-02,  4.36557382e-02,  3.99109721e-02,
         6.80547920e-35,  2.35433578e-02, -4.56788987e-02, -3.64247039e-02,
         3.97049561e-02, -2.14084405e-02, -1.54700631e-03,  9.18157995e-02,
        -7.23868189e-03,  7.68454932e-03,  2.62084696e-02, -2.25907401e-03],
       dtype=float32)]

In [53]:
import numpy as np
svector = np.array(vector).reshape(1, -1)
svector.shape

(1, 768)

In [55]:
vectors

array([[-0.00247394,  0.03626724, -0.0529046 , ..., -0.09152356,
        -0.0397    , -0.04330488],
       [-0.0335727 ,  0.00980516, -0.03250131, ..., -0.05165464,
         0.02245888, -0.03156181],
       [-0.01865323, -0.04051316, -0.01235386, ...,  0.00610587,
        -0.07179647,  0.02773852],
       ...,
       [-0.0006646 ,  0.04252128, -0.05645508, ...,  0.0131547 ,
        -0.0318357 , -0.04357662],
       [-0.03317151,  0.03252458, -0.0248484 , ...,  0.01174421,
         0.05747123,  0.00571023],
       [-0.00166393,  0.00413827, -0.04597083, ...,  0.02008528,
         0.05656241, -0.00161595]], shape=(8, 768), dtype=float32)

In [57]:
distances, I = index.search(svector, k=2)

In [58]:
I

array([[3, 2]])

In [59]:
df.loc[[3,2]]

                                                text category
3  Vibrant color jeans for male are becoming a trend  Fashion
2  These are the latest fashion trends for this week  Fashion

In [61]:
import os
from dotenv import load_dotenv
from langchain_openai import ChatOpenAI
load_dotenv()
api_key = os.getenv("OPENAI_KEY")

In [63]:
llm  = ChatOpenAI(
    temperature=0.9,
    api_key=api_key
)

In [ ]:
loader = UnstructuredURLLoader(urls = [
    "https://www.moneycontrol.com/news/",
    "https://www.moneycontrol.com/"   

])
data = loader.load()